<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asciidoc</string>
	</array>
	<key>name</key>
	<string>AsciiDoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>comment</key>
			<string>to prevent single-italic etc from crossing paragraph boundaries,
				we define paragraph boundaries and include single-italic etc within them</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>punctuation.test</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>includenot</key>
					<string>#single_italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_bold</string>
				</dict>
				<dict>
					<key>includenot</key>
					<string>#single_literal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^&lt;\d+?&gt;\s.*?$</string>
			<key>name</key>
			<string>markup.list.numbered.callout.asciidoc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>single_bold</key>
		<dict>
			<key>begin</key>
			<string>\*</string>
			<key>beginnot</key>
			<string>(?&lt;!\*|\g&lt;delim&gt;)(?&lt;delim&gt;\*)(?!\g&lt;delim&gt;|\s)</string>
			<key>end</key>
			<string>\*</string>
			<key>endnot</key>
			<string>(?&lt;!\g&lt;delim&gt;|\s)(?&lt;delim&gt;\*)(?!\g&lt;delim&gt;|\w)</string>
			<key>name</key>
			<string>markup.bold.asciidoc</string>
			<key>patternsnot</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single_italic</string>
				</dict>
			</array>
		</dict>
		<key>single_italicnot</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\*|\g&lt;delim&gt;)(?&lt;delim&gt;_)(?!\g&lt;delim&gt;|\s).*?(?&lt;!\g&lt;delim&gt;|\s)\g&lt;delim&gt;(?!\g&lt;delim&gt;|\w)</string>
			<key>name</key>
			<string>markup.italic.asciidoc</string>
		</dict>
		<key>single_literalnot</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\*|\g&lt;delim&gt;)(?&lt;delim&gt;\+)(?!\g&lt;delim&gt;|\s).*?(?&lt;!\g&lt;delim&gt;|\s)\g&lt;delim&gt;(?!\g&lt;delim&gt;|\w)</string>
			<key>name</key>
			<string>markup.literal.asciidoc</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.asciidoc</string>
	<key>uuid</key>
	<string>961C6043-B725-4E2D-83E8-114BF3A7389D</string>
</dict>
</plist>
